### ISSUE TITLE
mixin Conflict with blind's music disc 2.0

### ISSUE THREAD

**Issue by uczpre** [devOS-Sanity-Edition/blocky-bass#1]
try it yourself ;D

**Comment by TropheusJ** [comment]
That mod does an [override in it's mixin](https://github.com/theblindband/BlindsMusicDiscs/blob/8c25df0397dbdf92f536585ebb2925c391912d82/src/main/java/net/theblindbandit6/blindsmusicdiscs/mixin/MusicDiscItemMixin.java#L27), which is one of the most incompatible things a mod is able to do.
Report to them, nothing we can do

**Comment by theblindband** [comment]
The mixin override in my mod changes the music discs to work with a block tag rather than checking for specific blocks.
You can add your custom jukebox to the block tag and see if that works.
The block tag can be found [here](https://github.com/theblindband/BlindsMusicDiscs/blob/8c25df0397dbdf92f536585ebb2925c391912d82/src/main/generated/data/blindsmusicdiscs/tags/blocks/jukeboxes.json)

**Comment by TropheusJ** [comment]
Us adding a workaround is not a solution. What if I wanted to have a disc with durability? You need to fix your compatibility, it’s dead simple. You can just copy [what I did](https://github.com/devOS-Sanity-Edition/blocky-bass/blob/1.20.4/src/main/java/one/devos/nautical/blocky_bass/mixin/RecordItemMixin.java).

**Comment by theblindband** [comment]
Fixed this on my end now.
I genuinely didn't understand the problem so I'm sorry for taking so long.
